### PR TITLE
Issue46

### PR DESCRIPTION
**Pull request by OOlsen**
Each connection has a timertask for cleanup now.

### CODE REVIEW

**Comment by uweschaefer** [comment]
sorry, circleCI is picky about memory. i'll check manually tomorrow.

**Comment by uweschaefer** [comment]
THANKS!

I'll merge this as an urgent fix, but if you have time, you might want to consider to refactor to ScheduledThreadPoolExecutor.

**Comment by uweschaefer** [comment]
Furthermore, would it be a good ideaa to externalize the 10-Seconds interval to a configuration property?
It seems like a reasonable default, but having this configurable might be of value.

**Comment by OOlsen** [comment]
I wil do that.

**Pull request merged**
